- name: Install build dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ rbenv_debian_build_dependencies }}"
  become: "{{ rbenv_nonroot }}"
  when: rbenv_is_dependencies_installed
