---
# tasks file for rbenv
- name: ghq root
  shell: "{{ghq_executable}} root"
  register: ghq_root
  changed_when: false
- name: Clone rbenv and ruby-build repository
  ghq:
    executable: "{{ghq_executable}}"
    name: "{{item}}"
    update: yes
  with_items:
  - rbenv/rbenv
  - rbenv/ruby-build
- name: Check ~/.rbenv
  stat:
    path: "{{ansible_env.HOME}}/.rbenv"
  register: st
- name: Back up ~/.rbenv
  shell: "mv {{ansible_env.HOME}}/.rbenv {{ansible_env.HOME}}/.rbenv.{{ansible_date_time.date}}-{{ansible_date_time.hour}}-{{ansible_date_time.minute}}-{{ansible_date_time.second}}"
  when: st.stat.exists and not st.stat.islnk
- name: Make symbolic links
  file:
    src: "{{ghq_root.stdout}}/github.com/rbenv/rbenv"
    dest: "{{ansible_env.HOME}}/.rbenv"
    state: link
- name: mkdir ~/.rbenv/plugins
  file:
    path: "{{ansible_env.HOME}}/.rbenv/plugins"
    state: directory
- name: Check ~/.rbenv/plugins/ruby-build
  stat:
    path: "{{ansible_env.HOME}}/.rbenv/plugins/ruby-build"
  register: st
- name: Back up ~/.rbenv/plugins/ruby-build
  shell: "mv {{ansible_env.HOME}}/.rbenv/plugins/ruby-build {{ansible_env.HOME}}/.rbenv/plugins/ruby-build.{{ansible_date_time.date}}-{{ansible_date_time.hour}}-{{ansible_date_time.minute}}-{{ansible_date_time.second}}"
  when: st.stat.exists and not st.stat.islnk
- name: Make symbolic links
  file:
    src: "{{ghq_root.stdout}}/github.com/rbenv/ruby-build"
    dest: "{{ansible_env.HOME}}/.rbenv/plugins/ruby-build"
    state: link
- name: Notice
  debug:
    msg: "cd ~/.rbenv && src/configure && make -C src"
- name: Notice
  debug:
    msg: "Install rbenv install dependencies."
- name: Notice
  debug:
    msg: "export PATH=$HOME/.rbenv/bin:$PATH"
- name: Notice
  debug:
    msg: "eval \"$(rbenv init -)\""
