---
# tasks file for rbenv
- name: Create directories
  file:
    dest: "{{ rbenv_root | dirname }}"
    state: directory
- name: Clone rbenv
  git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ rbenv_root }}"
    version: "{{ rbenv_version }}"
    update: "{{ rbenv_update }}"
- name: Create directories
  file:
    dest: "{{ rbenv_root | dirname }}/plugins"
    state: directory
- name: Clone ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build
    dest: "{{ rbenv_root }}/plugins/ruby-build"
- block:
  - name: Add configurations to ~/.bashrc, ~/.profile, or ~/.zshrc or etc
    lineinfile:
      dest: "{{ rbenv_rc_path }}"
      line: 'export RBENV_ROOT="{{ rbenv_root }}"'
      regexp: '^export RBENV_ROOT='
      create: yes
  - name: Add configurations to ~/.bashrc, ~/.profile, or ~/.zshrc or etc
    lineinfile:
      dest: "{{ rbenv_rc_path }}"
      line: 'export PATH="$RBENV_ROOT/bin:$PATH"'
      create: yes
  - name: Add configurations to ~/.bashrc, ~/.profile, or ~/.zshrc or etc
    lineinfile:
      dest: "{{ rbenv_rc_path }}"
      line: 'eval "$(rbenv init -)"'
      create: yes
  when: rbenv_rc_path != "NOT ADD"
- include: "{{ rbenv_os_families.get(ansible_os_family, 'default') }}.yml"
  static: no
  when: rbenv_is_dependencies_installed and ansible_os_family in rbenv_os_families
