- name: Install build dependencies
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ rbenv_redhat_build_dependencies }}"
  become: "{{ rbenv_nonroot }}"
  when: rbenv_is_dependencies_installed
